<?php

use Illuminate\Database\Seeder;

class StatesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $states = [
            ['id'=>1, 'country_id'=>1, 'name'=>'Alabama'],
            ['id'=>2, 'country_id'=>1, 'name'=>'Alaska'],
            ['id'=>3, 'country_id'=>1, 'name'=>'Arizona'],
            ['id'=>4, 'country_id'=>1, 'name'=>'Arkansas'],
            ['id'=>5, 'country_id'=>1, 'name'=>'California'],
            ['id'=>6, 'country_id'=>1, 'name'=>'Colorado'],
            ['id'=>7, 'country_id'=>1, 'name'=>'Connecticut'],
            ['id'=>8, 'country_id'=>1, 'name'=>'Delaware'],
            ['id'=>9, 'country_id'=>1, 'name'=>'Florida'],
            ['id'=>10, 'country_id'=>1, 'name'=>'Georgia'],
            ['id'=>11, 'country_id'=>1, 'name'=>'Hawaii'],
            ['id'=>12, 'country_id'=>1, 'name'=>'Idaho'],
            ['id'=>13, 'country_id'=>1, 'name'=>'Illinois'],
            ['id'=>14, 'country_id'=>1, 'name'=>'Indiana'],
            ['id'=>15, 'country_id'=>1, 'name'=>'Iowa'],
            ['id'=>16, 'country_id'=>1, 'name'=>'Kansas'],
            ['id'=>17, 'country_id'=>1, 'name'=>'Kentucky'],
            ['id'=>18, 'country_id'=>1, 'name'=>'Louisiana'],
            ['id'=>19, 'country_id'=>1, 'name'=>'Maine'],
            ['id'=>20, 'country_id'=>1, 'name'=>'Maryland'],
            ['id'=>21, 'country_id'=>1, 'name'=>'Massachusetts'],
            ['id'=>22, 'country_id'=>1, 'name'=>'Michigan'],
            ['id'=>23, 'country_id'=>1, 'name'=>'Minnesota'],
            ['id'=>24, 'country_id'=>1, 'name'=>'Mississippi'],
            ['id'=>25, 'country_id'=>1, 'name'=>'Missouri'],
            ['id'=>26, 'country_id'=>1, 'name'=>'Montana'],
            ['id'=>27, 'country_id'=>1, 'name'=>'Nebraska'],
            ['id'=>28, 'country_id'=>1, 'name'=>'Nevada'],
            ['id'=>29, 'country_id'=>1, 'name'=>'New Hampshire'],
            ['id'=>30, 'country_id'=>1, 'name'=>'New Jersey'],
            ['id'=>31, 'country_id'=>1, 'name'=>'New Mexico'],
            ['id'=>32, 'country_id'=>1, 'name'=>'New York'],
            ['id'=>33, 'country_id'=>1, 'name'=>'North Carolina'],
            ['id'=>34, 'country_id'=>1, 'name'=>'North Dakota'],
            ['id'=>35, 'country_id'=>1, 'name'=>'Ohio'],
            ['id'=>36, 'country_id'=>1, 'name'=>'Oklahoma'],
            ['id'=>37, 'country_id'=>1, 'name'=>'Oregon'],
            ['id'=>38, 'country_id'=>1, 'name'=>'Pennsylvania'],
            ['id'=>39, 'country_id'=>1, 'name'=>'Rhode Island'],
            ['id'=>40, 'country_id'=>1, 'name'=>'South Carolina'],
            ['id'=>41, 'country_id'=>1, 'name'=>'South Dakota'],
            ['id'=>42, 'country_id'=>1, 'name'=>'Tennessee'],
            ['id'=>43, 'country_id'=>1, 'name'=>'Texas'],
            ['id'=>44, 'country_id'=>1, 'name'=>'Utah'],
            ['id'=>45, 'country_id'=>1, 'name'=>'Vermont'],
            ['id'=>46, 'country_id'=>1, 'name'=>'Virginia'],
            ['id'=>47, 'country_id'=>1, 'name'=>'Washington'],
            ['id'=>48, 'country_id'=>1, 'name'=>'West Virginia'],
            ['id'=>49, 'country_id'=>1, 'name'=>'Wisconsin'],
            ['id'=>50, 'country_id'=>1, 'name'=>'Wyoming'],
            ['id'=>51, 'country_id'=>1, 'name'=>'District of Columbia'],
            ['id'=>52, 'country_id'=>1, 'name'=>'Puerto Rico'],
            ['id'=>53, 'country_id'=>1, 'name'=>'Guam'],
            ['id'=>54, 'country_id'=>2, 'name'=>'Andhra Pradesh'],
            ['id'=>55, 'country_id'=>2, 'name'=>'Arunachai Pradesh'],
            ['id'=>56, 'country_id'=>2, 'name'=>'Assam'],
            ['id'=>57, 'country_id'=>2, 'name'=>'Bihar'],
            ['id'=>58, 'country_id'=>2, 'name'=>'Chhattisgarh'],
            ['id'=>59, 'country_id'=>2, 'name'=>'Goa'],
            ['id'=>60, 'country_id'=>2, 'name'=>'Gujarat'],
            ['id'=>61, 'country_id'=>2, 'name'=>'Haryana'],
            ['id'=>62, 'country_id'=>2, 'name'=>'Himachal Pradesh'],
            ['id'=>63, 'country_id'=>2, 'name'=>'Jammu and Kashmir'],
            ['id'=>64, 'country_id'=>2, 'name'=>'Jharkhand'],
            ['id'=>65, 'country_id'=>2, 'name'=>'Karnataka'],
            ['id'=>66, 'country_id'=>2, 'name'=>'Kerala'],
            ['id'=>67, 'country_id'=>2, 'name'=>'Madhya Pradesh'],
            ['id'=>68, 'country_id'=>2, 'name'=>'Maharashtra'],
            ['id'=>69, 'country_id'=>2, 'name'=>'Manipur'],
            ['id'=>70, 'country_id'=>2, 'name'=>'Meghalaya'],
            ['id'=>71, 'country_id'=>2, 'name'=>'Mizoram'],
            ['id'=>72, 'country_id'=>2, 'name'=>'Nagaland'],
            ['id'=>73, 'country_id'=>2, 'name'=>'Odisha'],
            ['id'=>74, 'country_id'=>2, 'name'=>'Punjab'],
            ['id'=>75, 'country_id'=>2, 'name'=>'Rajasthan'],
            ['id'=>76, 'country_id'=>2, 'name'=>'Sikkim'],
            ['id'=>77, 'country_id'=>2, 'name'=>'Tamil Nadu'],
            ['id'=>78, 'country_id'=>2, 'name'=>'Telangana'],
            ['id'=>79, 'country_id'=>2, 'name'=>'Tripura'],
            ['id'=>80, 'country_id'=>2, 'name'=>'Uttar Pradesh'],
            ['id'=>81, 'country_id'=>2, 'name'=>'Uttarakhand'],
            ['id'=>82, 'country_id'=>2, 'name'=>'West Bengal'],
            ['id'=>83, 'country_id'=>3, 'name'=>'Azad Jammu and Kashmir'],
            ['id'=>84, 'country_id'=>3, 'name'=>'Balochistan'],
            ['id'=>85, 'country_id'=>3, 'name'=>'Federally Administered Tribal Areas'],
            ['id'=>86, 'country_id'=>3, 'name'=>'Gilgit-Baltistan'],
            ['id'=>87, 'country_id'=>3, 'name'=>'Islamabad Capital Territory'],
            ['id'=>88, 'country_id'=>3, 'name'=>'Khyber Pakhtunkhwa'],
            ['id'=>89, 'country_id'=>3, 'name'=>'Punjab'],
            ['id'=>90, 'country_id'=>3, 'name'=>'Sindh'],
            ['id'=>91, 'country_id'=>4, 'name'=>'Luzon'],
            ['id'=>92, 'country_id'=>4, 'name'=>'Visayas'],
            ['id'=>93, 'country_id'=>4, 'name'=>'Mindanao'],
            ['id'=>94, 'country_id'=>5, 'name'=>'Abia'],
            ['id'=>95, 'country_id'=>5, 'name'=>'Adamawa'],
            ['id'=>96, 'country_id'=>5, 'name'=>'Anambra'],
            ['id'=>97, 'country_id'=>5, 'name'=>'Akwa'],
            ['id'=>98, 'country_id'=>5, 'name'=>'Ibom'],
            ['id'=>99, 'country_id'=>5, 'name'=>'Bauchi'],
            ['id'=>100, 'country_id'=>5, 'name'=>'Bayelsa'],
            ['id'=>101, 'country_id'=>5, 'name'=>'Benue'],
            ['id'=>102, 'country_id'=>5, 'name'=>'Borno'],
            ['id'=>103, 'country_id'=>5, 'name'=>'Cross River'],
            ['id'=>104, 'country_id'=>5, 'name'=>'Delta'],
            ['id'=>105, 'country_id'=>5, 'name'=>'Ebonyi'],
            ['id'=>106, 'country_id'=>5, 'name'=>'Enugu'],
            ['id'=>107, 'country_id'=>5, 'name'=>'Edo'],
            ['id'=>108, 'country_id'=>5, 'name'=>'Ekiti'],
            ['id'=>109, 'country_id'=>5, 'name'=>'Gombe'],
            ['id'=>110, 'country_id'=>5, 'name'=>'Imo'],
            ['id'=>111, 'country_id'=>5, 'name'=>'Jigawa'],
            ['id'=>112, 'country_id'=>5, 'name'=>'Kaduna'],
            ['id'=>113, 'country_id'=>5, 'name'=>'Kano'],
            ['id'=>114, 'country_id'=>5, 'name'=>'Katsina'],
            ['id'=>115, 'country_id'=>5, 'name'=>'Kebbi'],
            ['id'=>116, 'country_id'=>5, 'name'=>'Kogi'],
            ['id'=>117, 'country_id'=>5, 'name'=>'Kwara'],
            ['id'=>118, 'country_id'=>5, 'name'=>'Lagos'],
            ['id'=>119, 'country_id'=>5, 'name'=>'Nasarawa'],
            ['id'=>120, 'country_id'=>5, 'name'=>'Niger'],
            ['id'=>121, 'country_id'=>5, 'name'=>'Ogun'],
            ['id'=>122, 'country_id'=>5, 'name'=>'Ondo'],
            ['id'=>123, 'country_id'=>5, 'name'=>'Osun'],
            ['id'=>124, 'country_id'=>5, 'name'=>'Oyo'],
            ['id'=>125, 'country_id'=>5, 'name'=>'Plateau'],
            ['id'=>126, 'country_id'=>5, 'name'=>'Rivers'],
            ['id'=>127, 'country_id'=>5, 'name'=>'Sokoto'],
            ['id'=>128, 'country_id'=>5, 'name'=>'Taraba'],
            ['id'=>129, 'country_id'=>5, 'name'=>'Yobe'],
            ['id'=>130, 'country_id'=>5, 'name'=>'Zamfara'],
            ['id'=>131, 'country_id'=>6, 'name'=>'England'],
            ['id'=>132, 'country_id'=>6, 'name'=>'Scotland'],
            ['id'=>133, 'country_id'=>6, 'name'=>'Wales'],
            ['id'=>134, 'country_id'=>6, 'name'=>'Northern Ireland'],
            ['id'=>135, 'country_id'=>7, 'name'=>'Ångermanland'],
            ['id'=>136, 'country_id'=>7, 'name'=>'Blekinge'],
            ['id'=>137, 'country_id'=>7, 'name'=>'Bohuslän'],
            ['id'=>138, 'country_id'=>7, 'name'=>'Dalarna'],
            ['id'=>139, 'country_id'=>7, 'name'=>'Dalsland'],
            ['id'=>140, 'country_id'=>7, 'name'=>'Gotland'],
            ['id'=>141, 'country_id'=>7, 'name'=>'Gästrikland'],
            ['id'=>142, 'country_id'=>7, 'name'=>'Halland'],
            ['id'=>143, 'country_id'=>7, 'name'=>'Hälsingland'],
            ['id'=>144, 'country_id'=>7, 'name'=>'Härjedalen'],
            ['id'=>145, 'country_id'=>7, 'name'=>'Jämtland'],
            ['id'=>146, 'country_id'=>7, 'name'=>'Lappland'],
            ['id'=>147, 'country_id'=>7, 'name'=>'Medelpad'],
            ['id'=>148, 'country_id'=>7, 'name'=>'Norrbotten'],
            ['id'=>149, 'country_id'=>7, 'name'=>'Närke'],
            ['id'=>150, 'country_id'=>7, 'name'=>'Öland'],
            ['id'=>151, 'country_id'=>7, 'name'=>'Östergötland'],
            ['id'=>152, 'country_id'=>7, 'name'=>'Skåne'],
            ['id'=>153, 'country_id'=>7, 'name'=>'Småland'],
            ['id'=>154, 'country_id'=>7, 'name'=>'Södermanland'],
            ['id'=>155, 'country_id'=>7, 'name'=>'Uppland'],
            ['id'=>156, 'country_id'=>7, 'name'=>'Värmland'],
            ['id'=>157, 'country_id'=>7, 'name'=>'Västmanland'],
            ['id'=>158, 'country_id'=>7, 'name'=>'Västerbotten'],
            ['id'=>159, 'country_id'=>7, 'name'=>'Västergötland'],
            ['id'=>160, 'country_id'=>8, 'name'=>'Drenthe'],
            ['id'=>161, 'country_id'=>8, 'name'=>'Flevoland'],
            ['id'=>162, 'country_id'=>8, 'name'=>'Friesland'],
            ['id'=>163, 'country_id'=>8, 'name'=>'Gelderland'],
            ['id'=>164, 'country_id'=>8, 'name'=>'Groningen'],
            ['id'=>165, 'country_id'=>8, 'name'=>'Limburg'],
            ['id'=>166, 'country_id'=>8, 'name'=>'North Brabant'],
            ['id'=>167, 'country_id'=>8, 'name'=>'North Holland'],
            ['id'=>168, 'country_id'=>8, 'name'=>'Overijssel'],
            ['id'=>169, 'country_id'=>8, 'name'=>'South Holland'],
            ['id'=>170, 'country_id'=>8, 'name'=>'Utrecht'],
            ['id'=>171, 'country_id'=>8, 'name'=>'Zeeland'],
            ['id'=>172, 'country_id'=>9, 'name'=>'Hovedstaden'],
            ['id'=>173, 'country_id'=>9, 'name'=>'Midtjylland'],
            ['id'=>174, 'country_id'=>9, 'name'=>'Nordjylland'],
            ['id'=>175, 'country_id'=>9, 'name'=>'Sjælland'],
            ['id'=>176, 'country_id'=>9, 'name'=>'Syddanmark'],
            ['id'=>177, 'country_id'=>10, 'name'=>'Nord-Noreg'],
            ['id'=>178, 'country_id'=>10, 'name'=>'Midt-Noreg'],
            ['id'=>179, 'country_id'=>10, 'name'=>'Agder'],
            ['id'=>180, 'country_id'=>10, 'name'=>'Vestlandet'],
            ['id'=>181, 'country_id'=>10, 'name'=>'Austlandet'],
            ['id'=>182, 'country_id'=>11, 'name'=>'Espoo'],
            ['id'=>183, 'country_id'=>11, 'name'=>'Tampere'],
            ['id'=>184, 'country_id'=>11, 'name'=>'Vantaa'],
            ['id'=>185, 'country_id'=>11, 'name'=>'Oulu'],
            ['id'=>186, 'country_id'=>11, 'name'=>'Turku'],
            ['id'=>187, 'country_id'=>11, 'name'=>'Jyväskylä'],
            ['id'=>188, 'country_id'=>11, 'name'=>'Lahti'],
            ['id'=>189, 'country_id'=>11, 'name'=>'Kuopio'],
            ['id'=>190, 'country_id'=>11, 'name'=>'Kouvola'],
            ['id'=>191, 'country_id'=>11, 'name'=>'Pori'],
            ['id'=>192, 'country_id'=>11, 'name'=>'Joensuu'],
            ['id'=>193, 'country_id'=>11, 'name'=>'Lappeenranta'],
            ['id'=>194, 'country_id'=>11, 'name'=>'Hämeenlinna'],
            ['id'=>195, 'country_id'=>11, 'name'=>'Vaasa'],
            ['id'=>196, 'country_id'=>12, 'name'=>'Baden-Württemberg'],
            ['id'=>197, 'country_id'=>12, 'name'=>'Bavaria'],
            ['id'=>198, 'country_id'=>12, 'name'=>'Berlin'],
            ['id'=>199, 'country_id'=>12, 'name'=>'Brandenburg'],
            ['id'=>200, 'country_id'=>12, 'name'=>'Bremen'],
            ['id'=>201, 'country_id'=>12, 'name'=>'Hamburg'],
            ['id'=>202, 'country_id'=>12, 'name'=>'Hesse'],
            ['id'=>203, 'country_id'=>12, 'name'=>'Lower Saxony'],
            ['id'=>204, 'country_id'=>12, 'name'=>'Mecklenburg-Vorpommern'],
            ['id'=>205, 'country_id'=>12, 'name'=>'North Rhine- Westphalia'],
            ['id'=>206, 'country_id'=>12, 'name'=>'Rhineland-Palatinate'],
            ['id'=>207, 'country_id'=>12, 'name'=>'Saarland'],
            ['id'=>208, 'country_id'=>12, 'name'=>'Saxony'],
            ['id'=>209, 'country_id'=>12, 'name'=>'Saxony-Anhalt'],
            ['id'=>210, 'country_id'=>12, 'name'=>'Schleswig-Holstein'],
            ['id'=>211, 'country_id'=>12, 'name'=>'Thuringia'],
            ['id'=>212, 'country_id'=>13, 'name'=>'Ontario'],
            ['id'=>213, 'country_id'=>13, 'name'=>'Quebec'],
            ['id'=>214, 'country_id'=>13, 'name'=>'Nova Scotia'],
            ['id'=>215, 'country_id'=>13, 'name'=>'New Brunswick'],
            ['id'=>216, 'country_id'=>13, 'name'=>'Manitoba'],
            ['id'=>217, 'country_id'=>13, 'name'=>'British Columbia'],
            ['id'=>218, 'country_id'=>13, 'name'=>'Prince Edward Island'],
            ['id'=>219, 'country_id'=>13, 'name'=>'Saskatchewan'],
            ['id'=>220, 'country_id'=>13, 'name'=>'Alberta'],
            ['id'=>221, 'country_id'=>13, 'name'=>'Newfoundland and Labrador'],
        ];

        foreach ($states as $state) {
            \App\Models\State::create($state);
        }
    }
}
