<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = [
            [
                'id' => 1,
                'social' => 'google',
                'sid' => '106210646430736383404',
                'verified_at' => date("Y-m-d H:i:s"),
                'activated_at' => date("Y-m-d H:i:s"),
                'first_name' => 'Super',
                'last_name' => 'Admin',
                'avatar' => 'http://18.219.131.135/images/avatar/admin.jpg',
                'show' => 1,
                'college' => 1489,
                'online' => 1
            ],
//            DEV DATA
//            [
//                'id' => 2,
//                'social' => 'google',
//                'sid' => '106765288134314951326',
//                'verified_at' => date("Y-m-d H:i:s"),
//                'activated_at' => date("Y-m-d H:i:s"),
//                'first_name' => 'Turtle',
//                'last_name' => 'Swanson',
//                'avatar' => 'http://18.219.131.135/images/icon/icon.png',
//                'show' => 1,
//                'college' => 1489,
//                'online' => 1
//            ],
//            [
//                'id' => 3,
//                'social' => 'twitter',
//                'sid' => '100004',
//                'verified_at' => date("Y-m-d H:i:s"),
//                'activated_at' => date("Y-m-d H:i:s"),
//                'first_name' => 'Dev',
//                'last_name' => 'Tester',
//                'avatar' => null,
//                'show' => 1,
//                'college' => 1489,
//                'online' => 1
//            ],
//            [
//                'id' => 4,
//                'social' => 'google',
//                'sid' => '100450210661703842552',
//                'verified_at' => date("Y-m-d H:i:s"),
//                'activated_at' => date("Y-m-d H:i:s"),
//                'first_name' => 'Michael',
//                'last_name' => 'Lee',
//                'avatar' => 'http://18.219.131.135/images/avatar/avatar_michael.jpg',
//                'show' => 1,
//                'college' => 1489,
//            ],
//            [
//                'id' => 5,
//                'social' => 'facebook',
//                'sid' => '330685224361832',
//                'verified_at' => date("Y-m-d H:i:s"),
//                'activated_at' => date("Y-m-d H:i:s"),
//                'first_name' => 'Antipova',
//                'last_name' => 'Polina',
//                'avatar' => 'http://18.219.131.135/images/avatar/avatar_antipova.jpg',
//                'show' => 1,
//                'college' => 1489,
//                'online' => 1
//            ],
//            [
//                'id' => 6,
//                'social' => 'google',
//                'sid' => '100006',
//                'verified_at' => date("Y-m-d H:i:s"),
//                'activated_at' => date("Y-m-d H:i:s"),
//                'first_name' => 'BingBing',
//                'last_name' => 'Fan',
//                'avatar' => 'http://18.219.131.135/images/avatar/fanbingbing.png',
//                'show' => 1,
//                'college' => 1489,
//                'online' => 1
//            ],
//            [
//                'id' => 7,
//                'social' => 'google',
//                'sid' => '100007',
//                'verified_at' => date("Y-m-d H:i:s"),
//                'activated_at' => date("Y-m-d H:i:s"),
//                'first_name' => 'Swift',
//                'last_name' => 'Talyor',
//                'avatar' => 'http://18.219.131.135/images/avatar/swifttaylor.png',
//                'show' => 1,
//                'college' => 1489,
//            ],
//            [
//                'id' => 8,
//                'social' => 'facebook',
//                'sid' => '100008',
//                'verified_at' => date("Y-m-d H:i:s"),
//                'activated_at' => date("Y-m-d H:i:s"),
//                'first_name' => 'Jack',
//                'last_name' => 'Ma',
//                'avatar' => 'http://18.219.131.135/images/avatar/Jack-Ma-300x300.jpg',
//                'show' => 1,
//                'college' => 1489,
//                'online' => 1
//            ],
//            [
//                'id' => 9,
//                'social' => 'twitter',
//                'sid' => '100009',
//                'verified_at' => date("Y-m-d H:i:s"),
//                'activated_at' => date("Y-m-d H:i:s"),
//                'first_name' => 'Sheryl',
//                'last_name' => 'Sandberg',
//                'avatar' => 'http://18.219.131.135/images/avatar/Sheryl-Sandberg-300x300.jpg',
//                'show' => 1,
//                'college' => 1489,
//            ],
//            [
//                'id' => 10,
//                'social' => 'google',
//                'sid' => '100010',
//                'verified_at' => date("Y-m-d H:i:s"),
//                'activated_at' => date("Y-m-d H:i:s"),
//                'first_name' => 'Bob',
//                'last_name' => 'Iger',
//                'avatar' => 'http://18.219.131.135/images/avatar/Bob-Iger-300x300.jpg',
//                'show' => 1,
//                'college' => 1489,
//                'online' => 1
//            ],
//            [
//                'id' => 11,
//                'social' => 'google',
//                'sid' => '100011',
//                'verified_at' => date("Y-m-d H:i:s"),
//                'activated_at' => date("Y-m-d H:i:s"),
//                'first_name' => 'Reed',
//                'last_name' => 'Hastings',
//                'avatar' => 'http://18.219.131.135/images/avatar/Reed-Hastings-300x300.jpg',
//                'show' => 1,
//                'college' => 1489,
//                'online' => 1
//            ],
//            [
//                'id' => 12,
//                'social' => 'google',
//                'sid' => '100012',
//                'verified_at' => date("Y-m-d H:i:s"),
//                'activated_at' => date("Y-m-d H:i:s"),
//                'first_name' => 'Mary',
//                'last_name' => 'Barra',
//                'avatar' => 'http://18.219.131.135/images/avatar/Mary-Barra-300x300.jpg',
//                'show' => 1,
//                'college' => 1489,
//            ],
//            [
//                'id' => 13,
//                'social' => 'facebook',
//                'sid' => '100013',
//                'verified_at' => date("Y-m-d H:i:s"),
//                'activated_at' => date("Y-m-d H:i:s"),
//                'first_name' => 'Reshma',
//                'last_name' => 'Saujani',
//                'avatar' => 'http://18.219.131.135/images/avatar/Reshma-Saujani-300x300.jpg',
//                'show' => 1,
//                'college' => 1489,
//            ],
//            [
//                'id' => 14,
//                'social' => 'twitter',
//                'sid' => '100014',
//                'verified_at' => date("Y-m-d H:i:s"),
//                'activated_at' => date("Y-m-d H:i:s"),
//                'first_name' => 'Huateng',
//                'last_name' => 'Ma',
//                'avatar' => 'http://18.219.131.135/images/avatar/Huateng-Ma-300x300.jpg',
//                'show' => 1,
//                'college' => 1489,
//            ],
//            [
//                'id' => 15,
//                'social' => 'google',
//                'sid' => '100015',
//                'verified_at' => date("Y-m-d H:i:s"),
//                'activated_at' => date("Y-m-d H:i:s"),
//                'first_name' => 'XiaoChong',
//                'last_name' => 'Wang',
//                'avatar' => 'http://18.219.131.135/images/avatar/XiaoChongWang.jpg',
//                'show' => 1,
//                'college' => 1489,
//                'online' => 1
//            ],
//            [
//                'id' => 16,
//                'social' => 'google',
//                'sid' => '100016',
//                'verified_at' => date("Y-m-d H:i:s"),
//                'activated_at' => date("Y-m-d H:i:s"),
//                'first_name' => 'Jan',
//                'last_name' => 'Koum',
//                'avatar' => 'http://18.219.131.135/images/avatar/Jan-Koum-300x300.jpg',
//                'show' => 1,
//                'college' => 1489,
//                'online' => 1
//            ],
//            [
//                'id' => 17,
//                'social' => 'google',
//                'sid' => '100017',
//                'verified_at' => date("Y-m-d H:i:s"),
//                'activated_at' => date("Y-m-d H:i:s"),
//                'first_name' => 'Elon',
//                'last_name' => 'Musk',
//                'avatar' => 'http://18.219.131.135/images/avatar/Elon-Musk-300x300.jpg',
//                'show' => 1,
//                'college' => 1489,
//                'online' => 1
//            ],
//            [
//                'id' => 18,
//                'social' => 'facebook',
//                'sid' => '100018',
//                'verified_at' => date("Y-m-d H:i:s"),
//                'activated_at' => date("Y-m-d H:i:s"),
//                'first_name' => 'Warren',
//                'last_name' => 'Buffett',
//                'avatar' => 'http://18.219.131.135/images/avatar/Warren-Buffett-300x300.jpg',
//                'show' => 1,
//                'college' => 1489,
//                'online' => 1
//            ],
//            [
//                'id' => 19,
//                'social' => 'twitter',
//                'sid' => '100019',
//                'verified_at' => date("Y-m-d H:i:s"),
//                'activated_at' => date("Y-m-d H:i:s"),
//                'first_name' => 'Jeff',
//                'last_name' => 'Weiner',
//                'avatar' => 'http://18.219.131.135/images/avatar/Jeff-Weiner.png',
//                'show' => 1,
//                'college' => 1489,
//                'online' => 1
//            ],
//            [
//                'id' => 20,
//                'social' => 'google',
//                'sid' => '100020',
//                'verified_at' => date("Y-m-d H:i:s"),
//                'activated_at' => date("Y-m-d H:i:s"),
//                'first_name' => 'Bree',
//                'last_name' => 'Steffen',
//                'avatar' => 'http://18.219.131.135/images/avatar/BreeSteffen.png',
//                'show' => 1,
//                'college' => 1489,
//                'online' => 1
//            ],
//            [
//                'id' => 21,
//                'social' => 'google',
//                'sid' => '100021',
//                'verified_at' => date("Y-m-d H:i:s"),
//                'activated_at' => date("Y-m-d H:i:s"),
//                'first_name' => 'Elena',
//                'last_name' => 'Thomas',
//                'avatar' => 'http://18.219.131.135/images/avatar/ElenaThomas.png',
//                'show' => 1,
//                'college' => 1489,
//                'online' => 1
//            ],
//            [
//                'id' => 22,
//                'social' => 'google',
//                'sid' => '100022',
//                'verified_at' => date("Y-m-d H:i:s"),
//                'activated_at' => date("Y-m-d H:i:s"),
//                'first_name' => 'Kaylee',
//                'last_name' => 'Norman',
//                'avatar' => 'http://18.219.131.135/images/avatar/KayleeNorman.png',
//                'show' => 1,
//                'college' => 1489,
//                'online' => 1
//            ],
//            [
//                'id' => 23,
//                'social' => 'facebook',
//                'sid' => '100023',
//                'verified_at' => date("Y-m-d H:i:s"),
//                'activated_at' => date("Y-m-d H:i:s"),
//                'first_name' => 'Alina',
//                'last_name' => 'Bailey',
//                'avatar' => 'http://18.219.131.135/images/avatar/AlinaBailey.png',
//                'show' => 1,
//                'college' => 1489,
//            ],
//            [
//                'id' => 24,
//                'social' => 'twitter',
//                'sid' => '100024',
//                'verified_at' => date("Y-m-d H:i:s"),
//                'activated_at' => date("Y-m-d H:i:s"),
//                'first_name' => 'Lina',
//                'last_name' => 'J',
//                'avatar' =>'http://18.219.131.135/images/avatar/LinaJ.jpg',
//                'show' => 1,
//                'college' => 1489,
//            ],
//            [
//                'id' => 25,
//                'social' => 'google',
//                'sid' => '100025',
//                'verified_at' => date("Y-m-d H:i:s"),
//                'activated_at' => date("Y-m-d H:i:s"),
//                'first_name' => 'Ming',
//                'last_name' => 'Jiang',
//                'avatar' => 'http://18.219.131.135/images/avatar/MingJiang.jpg',
//                'show' => 1,
//                'college' => 1489,
//                'online' => 1
//            ]
        ];

        foreach ($users as $user) {
            \App\Models\User::create($user);
        }
    }
}
