<?php

namespace config;

class Constants {


public static function Orgs() {
    return $ORGANIZATIONS = [
    
        
        'Alpha chi alpha',
        'Alpha chi Rho',
        'Alpha Delta Gamma',
        'Alpha Delta Phi',
        'Aerospace club',
        'African christian Fellowship',
        'African Students Association',
        'Alpha Chi Omega',
        'Alpha Epsilon Delta',
        'Alpha Epsilon Pi',
        'Alpha Gamma Omega',
        'Alpha Gamma Delta',
        'Alpha Kappa Delta',
        'Alpha Kappa Delta Phi',
        'Alpha Lambda Delta',
        'Alpha Omicron Pi',
        'Alpha Phi',
        'Alpha Phi Alpha Fraternity',
        'Alpha Phi Omega',
        'Alpha Psi Omega',
        'Alpha Sigma Kappa',
        'Alpha Sigma Phi',
        'Alpha Tau Omega',
        'AME Graduate Student Community',
        'Arabic Club',
        'Assoc of Drilling Engineers',
        'Assoc of Inside Sales Professionals',
        'Assoc of Petroleum Geologists',
        'American Association of Airport Executives',
        'American Cancer Society Relay for Life',
        'American Indian Science and Engineering Society',
        'American Indian Student Association',
        'American Indian Student Fellowship',
        'American Institute of Aeronautics and Astronautics',
        'American Institute of Architecture Students',
        'American Institute of Chemical Engineers',
        'American Marketing Association',
        'American Society for Microbiology',
        'American Society of Civil Engineers',
        'American Society of Landscape Architects',
        'Amnesty International',
        'Angolan Student Association',
        'Anime Society',
        'Anthropology Graduate Student Association',
        'APICS',
        'Arab Student Association',
        'Arashi Taiko',
        'Architectural Virtuosi',
        'Arnold Air Society',
        'Art Museum Ambassadors',
        'ASHRAE',
        'Asian American Student Association',
        'Assoc Friends of Venezuela',
        'Assoc of Adult Higher Education and Development',
        'Association for Computing Machinery',
        'Assoc of Fundraising Professionals',
        'Assoc of Geography Graduate Students',
        'Association of Transfer Students',
        'Autism Speaks',

            
                
                'Aviation Club',
        'Badminton Club',
        'Bahai Association',
        'Ballroom Dance Club',
        'Baptist Collegiate Ministries',
        'Beta Alpha Psi',
        'Beta Chi Theta',
        'Beta Theta Pi',
        'Biology Club',
        'Black Graduate Student Association',
        'Black Student Association',
        'Bolivian International Student Association',
        'Boomer Rocket Team',
        'Brazilian Student Association',
        'Brothers Under Christ',
        'Campus Activities Council',
        'Campus Cursive',
        'Catholic Student Association',
        'Central Asian Student Association',
        'Chess Club',
        'Chi Alpha Campus Ministries',
        'Chi Epsilon',
        'Chi Omega',
        'Childs Cup Full',
        'Chinese Christian Fellowship',
        'Chinese Language Club',
        'Christian Grads Fellowship',
        'Christians on Campus',
        'Circle K International',
        'Classical Archaeology Society',
        'Climbing Club',
        'College Broadcasters',
        'College Republicans',
        'Colleges Against Cancer',
        'Collegiate Entrepreneurs Organization',
        'Collegiate National Association for Music Education',
        'Colombian Student Association',
        'Communication Graduate Student Association',
        'Community Emergency Response Team',
        'Computer club',
        'Computer Science Graduate Student Association',
        'Computer Science Interview Preparation Club',
        'ConnectU',
        'Constitutional Studies Student Association',
        'Construction Students Association',
        'Counseling Student Association',
        'CRU',
        'Crew',
        'Crimson Chords',
        'Curling Club',
        'Cycling Club',
        'Delta Delta Delta',
        'Delta Epsilon Psi',
        'Delta Gamma',
        'Delta Phi Omega',
        'Delta Sigma Pi',
        'Delta Sigma Theta',
        'Delta Tau Delta',
        'Delta Upsilon',
        'Design for America',
        'Dialogue Student Association',
        'Disability Inclusion and Awareness',
        'Dream Outside the Box',
        'Ducks Unlimited',
        'Dungeons and Dragons',
        'Dyslexia Educational Support Community',
        'Earth and Energy Equal Opportunity Association',
        'Earth Rebirth',
        'Economics Club',
        'Educational Studies Association',
        'Enactus',
        'Energy Management Student Association',
        'Engineering Entrepreneurs Club',
        'Engineers Club',
        'English Club',
        'Environmental Science Student Association',
        'Equestrian Club',
        'Eta Kappa Nu',
        'Eta Sigma Phi',
        'Expressive Movement Initiative',
        'Filipino Student Association',
        'Finance Student Association',
        'Financial Risk Management Association',
        'Fishing Club',
        'Forum Dialogue Newspaper',
        'French Club',
        'Freshman Action Team',
        'Game Developers Association',
        'Gamma Beta',
        'Gamma Beta Phi',
        'Gamma Delta Pi',
        'Gamma Phi Beta',
        'Gentlemen in Purple',
        'Geographic Information Science Student Org',
        'Geography and Environmental Sustainability Club',
        'German Club',
        'Gift of Life',
        'Glee Club',
        'Global Brigades',
        'Global Intervarsity Christian Fellowship',
        'Go Club',
        'Golden Key Honor Society',
        'Graphic Design Association',
        'Habitat for Humanity',
        'Health and Exercise Science Student Association',
        'Health Occupation Student of America',
        'Hebrew Club',
        'Hillel Jewish Student Org',
        'Hispanic American Student Association',
        'History of Science Association',
        'Holocaust Remembrance Society',
        'Honors Student Association',
        'Housing Center Student Association',
        'Independent Greek Council',
        'India Student Association',
        'Infocus - Stories of Africa',
        'Information Professionals for Social Justice',
        'Informed Citizen Discussion Groups',
        'Institute for Operations Research and Management Sciences',
        'Institute of Electrical and Electronics Engineers',
        'Institute of Industrial Engineers',
        'Integrity Council',
        'Intercollegiate Athletics Administration Student Association',
        'Intercollegiate Legislature',
        'Interfraternity Council',
        'Interior Design Student Association',
        'International Advisory Committee',
        'International Business Association',
        'International Studies Graduate Association',
        'Internet club',
        'InterVarsity Christian Fellowship',
        'Iota Phi Theta',
        'Iranian Cultural Association',
        'Iranian Student Association',
        'Italian Club',
        'Japanese Club',
        'Japanese Student Association',
        'JC Penny Leadership Program',
        'Kappa Alpha Order',
        'Kappa Alpha Psi',
        'Kappa Alpha Theta',
        'Kappa Delta Chi Sorority',
        'Kappa Delta Pi Education Honor Society',
        'Kappa Gamma Epsilon',
        'Kappa Kappa Gamma',
        'Kappa Kappa Psi Band Fraternity',
        'Kappa Phi',
        'Kappa Sigma',
        'Korean Conversation Club',
        'Korean Student Association',
        'Lambda Chi Alpha',
        'Lambda Delta Psi Sorority',
        'Lambda Phi Epsilon',
        'Latin Dance Club',
        'Latinos Without Borders',
        'Latter-Day Saint Student Association',
        'Lebanese Student Association',
        'Library and Information Studies Students Association',
        'Malaysian Student Organization',
        'Management Information Systems Student Association',
        'Minority Association of Pre-Health Students',
        'Model United Nations',
        'Multicultural Greek Council',
        'Mumford Research Group',
        'Music Composition Club',
        'Music is Medicine',
        'Music Teachers National Association',
        'Muslim Student Association',
        'NAACP',
        'National Association of Hispanic Journalists',
        'National Merit Brawlers',
        'National Organization of Minority Architecture Students',
        'National Pan-Hellenic Council',
        'National Science Teachers Association',
        'National Society of Black Engineers',
        'National Society of Collegiate Scholars',
        'Nazarene Student Center',
        'Nepali Student Association',
        'Nonprofit Leadership Student Association',
        'Oklahoma Undergraduate India Society',
        'Omega Delta Phi',
        'Omega Psi Phi',
        'ONE Emergency Medical Services',
        'Orthodox Christian Fellowship',
        'OU Cousins',
        'Our Earth',
        'Our Mental Health',
        'Paleontology Club',
        'Pan American Student Association',
        'Panhellenic Association',
        'Paranormal Society',
        'Peruvian Student Association',
        'Phi Alpha',
        'Phi Alpha Theta',
        'Phi Beta Delta',
        'Phi Beta Sigma',
        'Phi Delta Alpha',
        'Phi Delta Theta',
        'Phi Gamma Delta',
        'Phi Kappa Psi',
        'Phi Kappa Sigma',
        'Phi Mu Alpha',
        'Phi Sigma Pi',
        'Pi Beta Phi',
        'Pi Kappa Phi',
        'Pi Tau Sigma',
        'Pick and Hammer Club',
        'Poetry Slam',
        'Pre Physical Therapy Club',
        'Pre-Chiropractic Club',
        'Pre-Communication Sciences Disorders Club',
        'Pre-Dental Club',
        'Pre-Law Society',
        'Pre-Medical Professions Club',
        'Pre-Nursing Club',
        'Pre-Optometry Club',
        'Pre-Pharmacy Association',
        'Pre-Physician Assistant Club',
        'Pre-Veterinary Club',
        'Precision Dance Team',
        'Print Club',
        'Psychology Club',
        'Psychology Graduate Student Association',
        'Public Relations Students Society of America',
        'Pursuit College Ministry',
        'Queer Student Association',
        'Quidditch',
        'Reformed University Fellowship',
        'Robotics Club',
        'Rotary International',
        'Rugby team',
        'Russian Club',
        'Russian Speaking Student Association',
        'Sailing Club',
        'Saudi Student Association',
        'School of Meteorology Student Affairs Committee',
        'Scientific Research Discovery and Discussion',
        'Second Wind Student Group',
        'Secular Sooners',
        'SGA and Campus Elections',
        'SGA Budgetary Committee',
        'SGA Executive Branch',
        'SGA General Counsel',
        'SGA Graduate Student Senate',
        'SGA Undergraduate Student Congress',
        'Sigma Alpha Iota Music Fraternity',
        'Sigma Alpha Lambda',
        'Sigma Chi',
        'Sigma Gamma Rho',
        'Sigma Lambda Gamma',
        'Sigma Nu',
        'Sigma Nu Alpha Gamma',
        'Sigma Phi Epsilon',
        'Sigma Phi Lambda',
        'Society for Chemical and Biochemical Researchers',
        'Society of American Archivists Student Group',
        'Society of Asian Scientists & Engineers',
        'Society of Chinese Students and Scholars',
        'Society of Exploration Geophysicists',
        'Society of Hispanic Professional Engineers',
        'Society of Human Resource Management',
        'Society of Manufacturing Engineers',
        'Society of Native American Pre-Health Students',
        'Society of Petroleum Engineers',
        'Society of Petrophysicists and Well Log Analysts',
        'Society of Physics Students',
        'Society of Professional Journalists',
        'Society of Undergraduate Philosophers',
        'Society of Vietnamese Students',
        'Society of Women Engineers',
        'Sociology Graduate Student Board',
        'Sociology Criminology Club',
        'Sooner Air Traffic Control Association',
        'Sooner Information Network (SIN)',
        'South Asian InterVarsity Christian Fellowship',
        'Spanish Club',
        'Splash Squad',
        'Sports Management Club',
        'STEM Innovation',
        'Student African American Brotherhood',
        'Student Alumni Association',
        'Student Association of Bangladesh',
        'Student Athlete Advisory Committee',
        'Student Bar Association',
        'Student Business Association',
        'Student Consulting Group',
        'Student Council for Exceptional Children',
        'Student Dietetic Association',
        'Student Environmental Council',
        'Student Film Production Club',
        'Student Mobilization',
        'Student Education Association',
        'Student Planning Association',
        'Student Society of Human Relations',
        'Student Theatre Initiative',
        'Student Veterans of America',
        'Students for Education',
        'Students for Food Justice',
        'Students for Liberty',
        'Students for Social Justice',
        'Supercomputing Club',
        'Swahili Club',
        'Swim Club',
        'Tau Beta Pi Association',
        'Tau Beta Sigma',
        'Tau Kappa Omega',
        'Tau Kappa Epsilon',
        'Teach for America at OU',
        'The Other Film Club',
        'The Political Science Club',
        'The Red Clay Faction',
        'The Refinery',
        'The United World',
        'Tierra Tinta',
        'Triangle',
        'Triathlon Team',
        'Turkish Student Association',
        'US Green Building Council',
        'Undergraduate Anthropological Society',
        'Undergraduate Mathematics Club',
        'Ultimate Frisbee Club',
        'Ultimate Frisbee',
        'Union Programming Board',
        'United Campus Ministry',
        'University Gospel Choir',
        'Vietnamese Student Association',
        'Weather Lab',
        'Web design club',
        'Wesley Foundation',
        'Wildwood College Life',
        'WLT Book Club',
        'Women in Business Association',
        'Women in Electrical and Computer Engineering',
        'Women in Petroleum and Geological Engineering',
        'Women of Power',
        'Young Democrats',
        'Young Entrepreneurs',
        'Young Life College',
        'Zeta Phi Beta',
        'Army ROTC',
        'Air Force ROTC',
        'Navy ROTC',
        'Alpha Beta Chi',
        'Collegiate American Choral Directors Assoc',
    ];
    }
public static function Hobbies(){
    return $HOBBIES = [
            'Cooking',
            'Exercise',
            'Hiking',
            'Animal care',
            'Camping',
            'Boating',
            'Rock, Gem Finding',
            'Jewelery Making',
            'Volunteer Work',
            'Theater',
            'Photography',
            'Travel',
            'Craft beer',
            'Wine',
            'Hunting',
            'Archery',
            'Fishing',
            'Tattoo Artistry',
            'Astronomy',
            'Wood working',
            'Gardening',
            'Watching Movies',
            'Watching Sports',
            'Concerts',
            'Church Activities',
            'Family',
            'Sewing',
            'Crafts',
            'Drawing',
            'Painting',
            'Reading',
            'Writing',
            'Car mechanics',
            'Motorcycle mechanics',
            '3D printing',
            'Carpentry',
            'Woodworking',
            'RC vehicles',
            'Vocals / singer',
            'Guitar',
            'Harmonica',
            'Piano / Keyboard',
            'Saxophone',
            'Trumpet',
            'Tuba',
            'Flute',
            'Drums',
            'Violin',
            'Cello',
            'Clarinet',
            'Harp',
            'Basketball',
            'Ultimate Frisbee',
            'Disc Golf',
            'Running / Jogging',
            'Bicycling',
            'Soccer (futball)',
            'Hockey',
            'Volleyball',
            'Baseball',
            'Softball',
            'Tennis',
            'Swimming',
            'Dancing',
            'Field Hockey',
            'Cricket',
            'Martial Arts',
            'Boxing',
            'Auto Racing',
            'Lacrosse',
            'Track / Field',
            'Bowling',
            'Surfing',
            'Fishing',
            'Snowboarding',
            'Skiing',
            'Skate boarding',
            'Roller blading',
            'Golf',
            'Football',
            'Wrestling',
            'Racquetball',
            'Badminton',
            'Rowing',
            'Cornhole',
            'Billiards',
            'Table Tennis'
    
    ];
}
public static function Degrees(){
    return $DEGREES = [
            
            'Accounting',
            'Accounting BBA/MAcc',
            'Accounting IT',
            'Accounting Macro',
            'Accounting Accelerated',
            'Administrative Leadership',
            'Administrative Leadership Admin',
            'Adult and Higher Education',
            'Advertising',
            'Aerospace Engineering',
            'Aerospace Engineering Accelerated ',
            'Aerospace Engineering',
            'African and African-American Studies',
            'Anthropology',
            'Applied Linguistic Anthropology',
            'Arabic',
            'Architectural Engineering',
            'Architectural Civil Engineering',
            'Architecture',
            'Area Studies in Internationall Studies',
            'Art',
            'Art Technology and Culture',
            'Art Studio Arts ',
            'Art Visual Communication',
            'Art',
            'Art History',
            'Art History IT',
            'Asian Studies',
            'Astronomy',
            'Astrophysics',
            'Aviation Air Traffic',
            'Aviation Management',
            'Aviation Management Non-Flying Track',
            'Aviation Professional Pilot',
            'Ballet Pedagogy',
            'Ballet Performance',
            'Bassoon',
            'Biochemistry',
            'Biology',
            'Biology',
            'Biology Bioinformatics',
            'Biomedical Engineering',
            'Brass Instruments',
            'Business Administration MBA Industrial Engr BS',
            'Business Administration MBA Petroleum Engr BS',
            'Business Administration MBA Executive Energy',
            'Business Administration MBA Professional',
            'Business Administration MBA Standard',
            'Cello',
            'Chemical Biosciences',
            'Chemical Engineering Biotechnology',
            'Chemical Engineering Pre-Medical-Biomedical',
            'Chemical Engineering Standard',
            'Chemical Engineering Biomedical Engineering',
            'Chemical Engineering Biomedical Engineering',
            'Chemical Engineering Standard Accelerated',
            'Chemistry Professional',
            'Chemistry and Biochemistry Standard',
            'Chemistry',
            'Chemistry Bioinformatics',
            'Choral Conducting Music',
            'Chinese',
            'Civil Engineering',
            'Civil Engineering Accelerated',
            'Clarinet',
            'Classics Classical Languages',
            ' Classics Classical Studies',
            'Classics Latin',
            'Communication',
            'Communication Accelerated',
            'Communication Organizational Comm MA',
            'Composition',
            'Computer Engineering',
            'Computer Science',
            'Construction Management',
            'Construction Science',
            'Creative Media Production',
            'Criminal Justice Dance Ballet Pedagogy',
            'Dance Ballet Performance',
            'Dance Modern Dance Performance',
            'Dance MFA in Dance',
            'Data Science Analytics MS',
            'Double Bass',
            'Drama Theatre Acting Emphasis',
            'Drama Theatre Design Emphasis',
            'Drama Theatre Dramaturgy Emphasis',
            'Drama Theatre Scene Technology Emphasis',
            'Drama Theatre Stage Management Emphasis',
            'Early Childhood Education',
            'Early Childhood Birth through Third Grade',
            'Economics BA',
            'Economics Applied MA',
            'Economics Managerial MA',
            'Economics BBA',
            'Economics Management of Information Technology',
            'Education Administration Curriculum Supervision M Ed',
            'Educational Studies M Ed',
            'EIPT Educational Psychology M Ed',
            'EIPT Instructional Design Technology M Ed',
            'EIPT Integrating Technology in Teaching M Ed',
            'Electrical Engineering Standard',
            'Electrical Engineering Computer Engineering',
            'Elementary Education',
            'Elementary Education M Ed',
            'Energy Management',
            'Engineering MS',
            'Engineering Physics',
            'Engineering Physics MS',
            'English Literary and Cultural Studies',
            'English Writing',
            'English Writing Accelerated BA\/MA',
            'English Composition Rhetoric Literary Studies MA',
            'English Literary Studies MA',
            'English Education M Ed',
            'Entrepreneurship and Venture Management',
            'Entrepreneurship Management of Information Technology',
            'Environmental Design',
            'Environmental Engineering',
            'Environmental Engineering MS',
            'Environmental Geology',
            'Environmental Science',
            'Environmental Science MS',
            'Environmental Sustainability',
            'Environmental Technology MS',
            'Ethics and Religion',
            'European Studies',
            'European Studies Russian and East European',
            'Film and Media Studies',
            'Finance',
            'Finance Management of Information Technology',
            'Flute',
            'French',
            'French World Language Education',
            'Geographic Information Science',
            'Geography',
            'Geological Engineering',
            'Geology General Option',
            'Geology Paleontology Option',
            'Geology Petroleum Geology Option',
            'Geology MS',
            'Geophysics',
            'Geophysics MS',
            'German',
            'German MA',
            'German World Language Education',
            'Global Affairs MA',
            'Global Studies MA in Intl Studies',
            'Guitar',
            'Harp',
            'Health and Exercise Science',
            'Health and Exercise Science Exercise Physiology',
            'Health and Exercise Science Health Promotion',
            'History',
            'History of Science Technology and Medicine',
            'Human Health Services Administration MA',
            'Human Relations',
            'Human Relations MS Architectural Urban Studies',
            'Human Resources Management',
            'Human Resources Management of Information Technology',
            'Industrial and Systems Engineering',
            'Industrial and Systems Engineering Pre Medicine',
            'Industrial and Systems Engineering Analytics',
            'Information Studies',
            'Instructional Leadership M Ed',
            'Instrumental Conducting Music',
            'Instrumental Music Education',
            'Integrated Studies MA',
            'Interior Design',
            'International Relations MA',
            'International Security Studies',
            'International Studies',
            'Intercollegiate Athletics Administration',
            'International Business',
            'Italian',
            'Japanese',
            'Journalism and Mass Communication Advertising',
            'Journalism and Mass Communication Creative Media Production',
            'Journalism and Mass Communication Journalism',
            'Journalism and Mass Communication Professional Writing',
            'Journalism and Mass Communication Public Relations',
            'Journalism and Mass Communication MA',
            'Judaic Studies',
            'Landscape Architecture',
            'Language Arts Education',
            'Latin World Language Education',
            'Latin American Studies',
            'Letters',
            'Letters Constitutional Studies',
            'Liberal Studies Traditional and Electronic Delivery Options',
            'Library and Information Studies',
            'Lifespan Care Administration',
            'Linguistics',
            'Management General',
            'Management of Information Technology',
            'Management Information Systems',
            'Marketing',
            'Mathematics Professional',
            'Mathematics Standard',
            'Mathematics and Biostatistics',
            'Mathematics',
            'Mathematics Education',
            'Mechanical Engineering Premedical',
            'Mechanical Engineering Standard',
            'Mechanical Engineering',
            'Meteorology',
            'Microbiology Professional',
            'Microbiology Standard',
            'Microbiology Bioinformatics',
            'Middle Eastern Studies',
            'Modern Dance Performance',
            'Multidisciplinary Studies',
            'Multidisciplinary Studies',
            'Museum Studies',
            'Music BA',
            'Music BMA',
            'Music Brass and Percussion',
            'Music Composition',
            'Music Harp',
            'Music Organ',
            'Music Piano',
            'Music Piano',
            'Music Strings and Guitar',
            'Music Voice',
            'Music Woodwinds',
            'Music Education Conducting',
            'Music Education Instrumental',
            'Music Education Piano Pedagogy',
            'Music Education Vocal',
            'Music Theory',
            'Musical Theatre Performance',
            'Musicology',
            'Native American Studies',
            'Natural Gas Engineering',
            'Oboe',
            'Organ',
            'Organ Church',
            'Music',
            'Organ Technology Music',
            'Organizational Dynamics Human Resource Mgt',
            'Organizational Dynamics Technical Project Mgt',
            'Paleontology',
            'Percussion',
            'Petroleum Engineering',
            'Petroleum Geology',
            'Philosophy',
            'Physics Professional',
            'Physics Standard',
            'Piano',
            'Piano Pedagogy',
            'Piano Performance',
            'Piano Performance Pedagogy',
            'Planned Program BA',
            'Planned Program BS',
            'Planned Program Environmental Studies',
            'Planned Program Social Sciences and Organizational Studies',
            'Plant Biology Bioinformatics',
            'Political Science',
            'Political Science Public Administration',
            'Political Science Elections and Campaign Management',
            'Prevention Science',
            'Professional Counseling',
            'Professional Counseling Drug and Alcoho',
            'Professional Counseling School Counseling',
            'Professional Writing',
            'Psychology Professional',
            'Psychology Standard',
            'Psychology Industrial Organizatonal',
            'Public Administration',
            'Public Administration Individualized Intensive Study',
            'Public Administration Non-Profit Mgt',
            'Public Administration Public Policy',
            'Public Affairs and Administration',
            'Public Relations',
            'Reading Education',
            'Regional and City Planning',
            'Religious Studies',
            'Risk Management',
            'Risk Management of Information Technology',
            'Russian',
            'Saxophone',
            'Science Education Biological Sciences',
            'Science Education Chemistry',
            'Science Education Earth Science',
            'Science Education Physics',
            'Science Education Physical Science',
            'STEM Education',
            'Secondary Education',
            'Social Studies Education',
            'Social Work',
            'Social Work Advanced Standing Admin',
            'Social Work Direct Practice',
            'Social Work Advanced Standing Direct Practice',
            'Sociology Criminology',
            'Sociology General',
            'Sociology',
            'Spanish',
            'Spanish World Language Education',
            'Special Education',
            'Special Education Applied Behavior Analysis',
            'Special Education with Teacher Certification',
            'Special Education Secondary Transition',
            'Sports Management',
            'Studio Arts',
            'Supply Chain Management',
            'Supply Chain Management of Information Technology',
            'Teacher Education',
            'Telecommunications Engineering',
            'Theatre Acting Emphasis',
            'Theatre Design Emphasis',
            'Theatre Dramaturgy Emphasis',
            'Theatre Scene Technology',
            'Theatre Stage Management Emphasis',
            'Urban Studies Architectural Urban Studies',
            'Viola',
            'Violin',
            'Visual Communications Art',
            'Vocal Music Education',
            'Voice',
            'Voice Performance',
            'Voice Performance Opera',
            'Women\'s and Gender Studies',
            'World Cultural Studies',
            'World Language Education'
        ];
}
}